name: Ship

on:
  workflow_dispatch: # manual override
  schedule:
    - cron: "0 * * * *" # every hour

jobs:
  ship:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Deno repo
        uses: actions/checkout@v2
        with:
          repository: "denoland/deno"
          fetch-depth: 1
          submodules: false

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: "v1.5.4"

      - name: Check and publish
        run: |
          deno install -qA --unstable https://x.nest.land/eggs@0.3.2/eggs.ts
          eggs link ${{ secrets.NESTAPIKEY }}
          cd ./std
          deno run -qA --unstable https://github.com/nestdotland/std/raw/master/update.ts
